version: 2
project_name: pltf

builds:
  - id: pltf
    main: ./main.go
    binary: pltf
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
      - windows
    goarch:
      - amd64
      - arm64
    ldflags:
      - "-s -w"

archives:
  - id: pltf
    builds: [pltf]
    format_overrides:
      - goos: windows
        format: zip
    name_template: "{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}"

checksum:
  name_template: "checksums.txt"

brews:
  - ids: [pltf]
    homepage: "https://github.com/yindia/pltf"
    description: "pltf CLI turns Environment and Service YAML into validated Terraform."
    license: "MIT"
    directory: Formula
    repository:
      owner: "yindia"
      name: "pltf"
    test: |
      system "#{bin}/pltf", "--help"
    install: |
      bin.install "pltf"
changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"

release:
  github:
    owner: "yindia"
    name: "pltf"
  draft: true
