apiVersion: platform.io/v1
kind: Stack
metadata:
  name: k8s-observability
providers:
  kubernetes: true
  helm: true
variables:
  observability_namespace: "observability"
modules:
  - id: prometheus
    type: helm_chart
    inputs:
      chart: kube-prometheus-stack
      repository: https://prometheus-community.github.io/helm-charts
      namespace: var.observability_namespace
      create_namespace: true
  - id: grafana
    type: helm_chart
    inputs:
      chart: grafana
      repository: https://grafana.github.io/helm-charts
      namespace: var.observability_namespace
      create_namespace: true
