apiVersion: platform.io/v1
kind: Stack
metadata:
  name: k8s-nodegroup
variables:
  nodegroup_instance_type: "t3.medium"
modules:
  - id: nodegroup
    type: aws_nodegroup
    inputs:
      node_instance_type: var.nodegroup_instance_type
