# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Pltf < Formula
  desc "pltf CLI turns Environment and Service YAML into validated Terraform."
  homepage "https://github.com/yindia/pltf"
  version "0.0.2-beta"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/yindia/pltf/releases/download/v0.0.2-beta/pltf_0.0.2-beta_darwin_amd64.tar.gz"
      sha256 "c8409d75fbd5ece43e9fa840bdc4346a6ccf87ecc9f6f82903843e876d1b7be1"

      def install
        bin.install "pltf"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/yindia/pltf/releases/download/v0.0.2-beta/pltf_0.0.2-beta_darwin_arm64.tar.gz"
      sha256 "dbae4358deb12db9393b138d0007c5a2d8c132a59c28f2bee8b8d21ad2602b28"

      def install
        bin.install "pltf"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/yindia/pltf/releases/download/v0.0.2-beta/pltf_0.0.2-beta_linux_amd64.tar.gz"
      sha256 "af2a304589071f8ce887354109784e6199995211094f4d61cb7ea104bb9d061f"
      def install
        bin.install "pltf"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/yindia/pltf/releases/download/v0.0.2-beta/pltf_0.0.2-beta_linux_arm64.tar.gz"
      sha256 "d10f5c9e99bc43617839842051485b0a0b9e6ace95e4c95298f3fd1563935c39"
      def install
        bin.install "pltf"
      end
    end
  end

  test do
    system "#{bin}/pltf", "--help"
  end
end
