# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Pltf < Formula
  desc "pltf CLI turns Environment and Service YAML into validated Terraform."
  homepage "https://github.com/yindia/pltf"
  version "0.0.3-beta"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/yindia/pltf/releases/download/v0.0.3-beta/pltf_0.0.3-beta_darwin_amd64.tar.gz"
      sha256 "87d633f8a7aa67e5dbf4fdd62d54d1d1a66ab3f2f6909122044247eb47bb5a40"

      def install
        bin.install "pltf"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/yindia/pltf/releases/download/v0.0.3-beta/pltf_0.0.3-beta_darwin_arm64.tar.gz"
      sha256 "672251f48efd4262a26f13f09f962b5ab84f6864ace68f8cffc219f2c2c48708"

      def install
        bin.install "pltf"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/yindia/pltf/releases/download/v0.0.3-beta/pltf_0.0.3-beta_linux_amd64.tar.gz"
      sha256 "c97616b49a3673c3c63f2a5edc55be99ee4f2ef3196d09d19e6cb6aa57537567"
      def install
        bin.install "pltf"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/yindia/pltf/releases/download/v0.0.3-beta/pltf_0.0.3-beta_linux_arm64.tar.gz"
      sha256 "2d164abb7b04f56a737be7986e8ce521537e451ddb4ec97164c97c2f075b1560"
      def install
        bin.install "pltf"
      end
    end
  end

  test do
    system "#{bin}/pltf", "--help"
  end
end
