# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Pltf < Formula
  desc "pltf CLI turns Environment and Service YAML into validated Terraform."
  homepage "https://github.com/yindia/pltf"
  version "0.0.1-beta"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/yindia/pltf/releases/download/v0.0.1-beta/pltf_0.0.1-beta_darwin_amd64.tar.gz"
      sha256 "13733a97ab51c522a50889451fe4a44f8a05e5af5b75d881001ef2b3d7c82f85"

      def install
        bin.install "pltf"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/yindia/pltf/releases/download/v0.0.1-beta/pltf_0.0.1-beta_darwin_arm64.tar.gz"
      sha256 "d1ecc159175d799a7a4cbbe0de72e48752d2201b2c6cad164a4f2c4ea4154b43"

      def install
        bin.install "pltf"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/yindia/pltf/releases/download/v0.0.1-beta/pltf_0.0.1-beta_linux_amd64.tar.gz"
      sha256 "9f941cd430df1de0faa4402f324c3e6e3e0df58784fa26411526808f09a27bef"
      def install
        bin.install "pltf"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/yindia/pltf/releases/download/v0.0.1-beta/pltf_0.0.1-beta_linux_arm64.tar.gz"
      sha256 "2041907fc85f09ea6f5c3ecbea0bd1267a63bf3e35b108145b4e9a479fdbf544"
      def install
        bin.install "pltf"
      end
    end
  end

  test do
    system "#{bin}/pltf", "--help"
  end
end
